### ISSUE TITLE
`Tuple` should be exposed

### ISSUE THREAD

**Issue by crazymonkyyy** [opendlang/d#5]
``tuple` is not a type`

**Comment by adamdruppe** [comment]
tuple is, in fact, not a type. Tuple is though if it is imported.

**Comment by crazymonkyyy** [comment]
https://github.com/opendlang/d/blob/cd220e4b9d2f45ea6713e6bfa69d2a0216708a2a/source/odc/datastructures.d#L52

its currently a voldemore type
